services:
  app:
    container_name: sea-catering-app
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - DB_HOST=db
    depends_on:
      - db
    command: ["/app/server"]
  db:
    container_name: sea-catering-db
    image: postgres:16.1-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
